# build.yaml  – lives next to Dockerfile and config.json
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64:   ghcr.io/home-assistant/amd64-base:latest

args:
  OTBR_VERSION: "826ebdf363d926bef906f92a876a8540d9223d5a"   # 1.4-branch head
  UNIVERSAL_SILABS_FLASHER: "0.0.28"
